#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndOfDays
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CMD-FX")]
	public partial class CMDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPOS_PI(POS_PI instance);
    partial void UpdatePOS_PI(POS_PI instance);
    partial void DeletePOS_PI(POS_PI instance);
    partial void InsertPOS_PT(POS_PT instance);
    partial void UpdatePOS_PT(POS_PT instance);
    partial void DeletePOS_PT(POS_PT instance);
    partial void InsertPOS_PT_PR(POS_PT_PR instance);
    partial void UpdatePOS_PT_PR(POS_PT_PR instance);
    partial void DeletePOS_PT_PR(POS_PT_PR instance);
    #endregion
		
		public CMDDataContext() : 
				base(global::EndOfDays.Properties.Settings.Default.CMD_FXConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public CMDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CMDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CMDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CMDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<POS_PI> POS_PIs
		{
			get
			{
				return this.GetTable<POS_PI>();
			}
		}
		
		public System.Data.Linq.Table<POS_PT> POS_PTs
		{
			get
			{
				return this.GetTable<POS_PT>();
			}
		}
		
		public System.Data.Linq.Table<POS_PT_PR> POS_PT_PRs
		{
			get
			{
				return this.GetTable<POS_PT_PR>();
			}
		}
		
		public System.Data.Linq.Table<PV_POS_UL> PV_POS_ULs
		{
			get
			{
				return this.GetTable<PV_POS_UL>();
			}
		}
		
		public System.Data.Linq.Table<PV_None_Sync> PV_None_Syncs
		{
			get
			{
				return this.GetTable<PV_None_Sync>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PF_GET_SALES", IsComposable=true)]
		public IQueryable<PF_GET_SALESResult> PF_GET_SALES()
		{
			return this.CreateMethodCallQuery<PF_GET_SALESResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.POS_PI")]
	public partial class POS_PI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _WH_ID;
		
		private string _TMCODE;
		
		private string _ABBNO;
		
		private System.DateTime _PTDATE;
		
		private short _ITEMNO;
		
		private int _MP_ID;
		
		private int _BC_ID;
		
		private string _VATABLE;
		
		private string _CONTROLSN;
		
		private int _SH_ID;
		
		private System.Nullable<decimal> _ACPRICE;
		
		private short _PRICENO;
		
		private string _DPRICE;
		
		private string _BPRICE;
		
		private decimal _PRICE;
		
		private int _UM_ID;
		
		private decimal _UMRATIO;
		
		private decimal _QTY;
		
		private string _DISCOUNTSTR;
		
		private decimal _DISCOUNTAMT;
		
		private decimal _TOTAL;
		
		private decimal _NET;
		
		private System.Nullable<decimal> _VAL;
		
		private System.Nullable<decimal> _POINT;
		
		private string _PRCODE;
		
		private System.Nullable<int> _OFFERID;
		
		private string _ITEMAU;
		
		private System.Nullable<int> _ITEMRF;
		
		private System.Nullable<decimal> _QTY_RF;
		
		private System.Nullable<decimal> _PR_TOTAL;
		
		private System.Nullable<decimal> _PR_NET;
		
		private System.Nullable<decimal> _PR_VAL;
		
		private string _PIVOIDED;
		
		private string _PISTATUS;
		
		private System.DateTime _WORKDATE;
		
		private System.Nullable<decimal> _TAG_F;
		
		private string _TAG_S;
		
		private EntityRef<POS_PT> _POS_PT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWH_IDChanging(int value);
    partial void OnWH_IDChanged();
    partial void OnTMCODEChanging(string value);
    partial void OnTMCODEChanged();
    partial void OnABBNOChanging(string value);
    partial void OnABBNOChanged();
    partial void OnPTDATEChanging(System.DateTime value);
    partial void OnPTDATEChanged();
    partial void OnITEMNOChanging(short value);
    partial void OnITEMNOChanged();
    partial void OnMP_IDChanging(int value);
    partial void OnMP_IDChanged();
    partial void OnBC_IDChanging(int value);
    partial void OnBC_IDChanged();
    partial void OnVATABLEChanging(string value);
    partial void OnVATABLEChanged();
    partial void OnCONTROLSNChanging(string value);
    partial void OnCONTROLSNChanged();
    partial void OnSH_IDChanging(int value);
    partial void OnSH_IDChanged();
    partial void OnACPRICEChanging(System.Nullable<decimal> value);
    partial void OnACPRICEChanged();
    partial void OnPRICENOChanging(short value);
    partial void OnPRICENOChanged();
    partial void OnDPRICEChanging(string value);
    partial void OnDPRICEChanged();
    partial void OnBPRICEChanging(string value);
    partial void OnBPRICEChanged();
    partial void OnPRICEChanging(decimal value);
    partial void OnPRICEChanged();
    partial void OnUM_IDChanging(int value);
    partial void OnUM_IDChanged();
    partial void OnUMRATIOChanging(decimal value);
    partial void OnUMRATIOChanged();
    partial void OnQTYChanging(decimal value);
    partial void OnQTYChanged();
    partial void OnDISCOUNTSTRChanging(string value);
    partial void OnDISCOUNTSTRChanged();
    partial void OnDISCOUNTAMTChanging(decimal value);
    partial void OnDISCOUNTAMTChanged();
    partial void OnTOTALChanging(decimal value);
    partial void OnTOTALChanged();
    partial void OnNETChanging(decimal value);
    partial void OnNETChanged();
    partial void OnVALChanging(System.Nullable<decimal> value);
    partial void OnVALChanged();
    partial void OnPOINTChanging(System.Nullable<decimal> value);
    partial void OnPOINTChanged();
    partial void OnPRCODEChanging(string value);
    partial void OnPRCODEChanged();
    partial void OnOFFERIDChanging(System.Nullable<int> value);
    partial void OnOFFERIDChanged();
    partial void OnITEMAUChanging(string value);
    partial void OnITEMAUChanged();
    partial void OnITEMRFChanging(System.Nullable<int> value);
    partial void OnITEMRFChanged();
    partial void OnQTY_RFChanging(System.Nullable<decimal> value);
    partial void OnQTY_RFChanged();
    partial void OnPR_TOTALChanging(System.Nullable<decimal> value);
    partial void OnPR_TOTALChanged();
    partial void OnPR_NETChanging(System.Nullable<decimal> value);
    partial void OnPR_NETChanged();
    partial void OnPR_VALChanging(System.Nullable<decimal> value);
    partial void OnPR_VALChanged();
    partial void OnPIVOIDEDChanging(string value);
    partial void OnPIVOIDEDChanged();
    partial void OnPISTATUSChanging(string value);
    partial void OnPISTATUSChanged();
    partial void OnWORKDATEChanging(System.DateTime value);
    partial void OnWORKDATEChanged();
    partial void OnTAG_FChanging(System.Nullable<decimal> value);
    partial void OnTAG_FChanged();
    partial void OnTAG_SChanging(string value);
    partial void OnTAG_SChanged();
    #endregion
		
		public POS_PI()
		{
			this._POS_PT = default(EntityRef<POS_PT>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WH_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int WH_ID
		{
			get
			{
				return this._WH_ID;
			}
			set
			{
				if ((this._WH_ID != value))
				{
					if (this._POS_PT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnWH_IDChanging(value);
					this.SendPropertyChanging();
					this._WH_ID = value;
					this.SendPropertyChanged("WH_ID");
					this.OnWH_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TMCODE", DbType="VarChar(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TMCODE
		{
			get
			{
				return this._TMCODE;
			}
			set
			{
				if ((this._TMCODE != value))
				{
					if (this._POS_PT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTMCODEChanging(value);
					this.SendPropertyChanging();
					this._TMCODE = value;
					this.SendPropertyChanged("TMCODE");
					this.OnTMCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ABBNO", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ABBNO
		{
			get
			{
				return this._ABBNO;
			}
			set
			{
				if ((this._ABBNO != value))
				{
					if (this._POS_PT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnABBNOChanging(value);
					this.SendPropertyChanging();
					this._ABBNO = value;
					this.SendPropertyChanged("ABBNO");
					this.OnABBNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PTDATE", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime PTDATE
		{
			get
			{
				return this._PTDATE;
			}
			set
			{
				if ((this._PTDATE != value))
				{
					if (this._POS_PT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPTDATEChanging(value);
					this.SendPropertyChanging();
					this._PTDATE = value;
					this.SendPropertyChanged("PTDATE");
					this.OnPTDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEMNO", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short ITEMNO
		{
			get
			{
				return this._ITEMNO;
			}
			set
			{
				if ((this._ITEMNO != value))
				{
					this.OnITEMNOChanging(value);
					this.SendPropertyChanging();
					this._ITEMNO = value;
					this.SendPropertyChanged("ITEMNO");
					this.OnITEMNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MP_ID", DbType="Int NOT NULL")]
		public int MP_ID
		{
			get
			{
				return this._MP_ID;
			}
			set
			{
				if ((this._MP_ID != value))
				{
					this.OnMP_IDChanging(value);
					this.SendPropertyChanging();
					this._MP_ID = value;
					this.SendPropertyChanged("MP_ID");
					this.OnMP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BC_ID", DbType="Int NOT NULL")]
		public int BC_ID
		{
			get
			{
				return this._BC_ID;
			}
			set
			{
				if ((this._BC_ID != value))
				{
					this.OnBC_IDChanging(value);
					this.SendPropertyChanging();
					this._BC_ID = value;
					this.SendPropertyChanged("BC_ID");
					this.OnBC_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VATABLE", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string VATABLE
		{
			get
			{
				return this._VATABLE;
			}
			set
			{
				if ((this._VATABLE != value))
				{
					this.OnVATABLEChanging(value);
					this.SendPropertyChanging();
					this._VATABLE = value;
					this.SendPropertyChanged("VATABLE");
					this.OnVATABLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTROLSN", DbType="VarChar(1)")]
		public string CONTROLSN
		{
			get
			{
				return this._CONTROLSN;
			}
			set
			{
				if ((this._CONTROLSN != value))
				{
					this.OnCONTROLSNChanging(value);
					this.SendPropertyChanging();
					this._CONTROLSN = value;
					this.SendPropertyChanged("CONTROLSN");
					this.OnCONTROLSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SH_ID", DbType="Int NOT NULL")]
		public int SH_ID
		{
			get
			{
				return this._SH_ID;
			}
			set
			{
				if ((this._SH_ID != value))
				{
					this.OnSH_IDChanging(value);
					this.SendPropertyChanging();
					this._SH_ID = value;
					this.SendPropertyChanged("SH_ID");
					this.OnSH_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACPRICE", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> ACPRICE
		{
			get
			{
				return this._ACPRICE;
			}
			set
			{
				if ((this._ACPRICE != value))
				{
					this.OnACPRICEChanging(value);
					this.SendPropertyChanging();
					this._ACPRICE = value;
					this.SendPropertyChanged("ACPRICE");
					this.OnACPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRICENO", DbType="SmallInt NOT NULL")]
		public short PRICENO
		{
			get
			{
				return this._PRICENO;
			}
			set
			{
				if ((this._PRICENO != value))
				{
					this.OnPRICENOChanging(value);
					this.SendPropertyChanging();
					this._PRICENO = value;
					this.SendPropertyChanged("PRICENO");
					this.OnPRICENOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DPRICE", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string DPRICE
		{
			get
			{
				return this._DPRICE;
			}
			set
			{
				if ((this._DPRICE != value))
				{
					this.OnDPRICEChanging(value);
					this.SendPropertyChanging();
					this._DPRICE = value;
					this.SendPropertyChanged("DPRICE");
					this.OnDPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BPRICE", DbType="VarChar(1)")]
		public string BPRICE
		{
			get
			{
				return this._BPRICE;
			}
			set
			{
				if ((this._BPRICE != value))
				{
					this.OnBPRICEChanging(value);
					this.SendPropertyChanging();
					this._BPRICE = value;
					this.SendPropertyChanged("BPRICE");
					this.OnBPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRICE", DbType="Decimal(15,2) NOT NULL")]
		public decimal PRICE
		{
			get
			{
				return this._PRICE;
			}
			set
			{
				if ((this._PRICE != value))
				{
					this.OnPRICEChanging(value);
					this.SendPropertyChanging();
					this._PRICE = value;
					this.SendPropertyChanged("PRICE");
					this.OnPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UM_ID", DbType="Int NOT NULL")]
		public int UM_ID
		{
			get
			{
				return this._UM_ID;
			}
			set
			{
				if ((this._UM_ID != value))
				{
					this.OnUM_IDChanging(value);
					this.SendPropertyChanging();
					this._UM_ID = value;
					this.SendPropertyChanged("UM_ID");
					this.OnUM_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UMRATIO", DbType="Decimal(15,4) NOT NULL")]
		public decimal UMRATIO
		{
			get
			{
				return this._UMRATIO;
			}
			set
			{
				if ((this._UMRATIO != value))
				{
					this.OnUMRATIOChanging(value);
					this.SendPropertyChanging();
					this._UMRATIO = value;
					this.SendPropertyChanged("UMRATIO");
					this.OnUMRATIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTY", DbType="Decimal(15,4) NOT NULL")]
		public decimal QTY
		{
			get
			{
				return this._QTY;
			}
			set
			{
				if ((this._QTY != value))
				{
					this.OnQTYChanging(value);
					this.SendPropertyChanging();
					this._QTY = value;
					this.SendPropertyChanged("QTY");
					this.OnQTYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISCOUNTSTR", DbType="VarChar(80)")]
		public string DISCOUNTSTR
		{
			get
			{
				return this._DISCOUNTSTR;
			}
			set
			{
				if ((this._DISCOUNTSTR != value))
				{
					this.OnDISCOUNTSTRChanging(value);
					this.SendPropertyChanging();
					this._DISCOUNTSTR = value;
					this.SendPropertyChanged("DISCOUNTSTR");
					this.OnDISCOUNTSTRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISCOUNTAMT", DbType="Decimal(15,2) NOT NULL")]
		public decimal DISCOUNTAMT
		{
			get
			{
				return this._DISCOUNTAMT;
			}
			set
			{
				if ((this._DISCOUNTAMT != value))
				{
					this.OnDISCOUNTAMTChanging(value);
					this.SendPropertyChanging();
					this._DISCOUNTAMT = value;
					this.SendPropertyChanged("DISCOUNTAMT");
					this.OnDISCOUNTAMTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL", DbType="Decimal(15,2) NOT NULL")]
		public decimal TOTAL
		{
			get
			{
				return this._TOTAL;
			}
			set
			{
				if ((this._TOTAL != value))
				{
					this.OnTOTALChanging(value);
					this.SendPropertyChanging();
					this._TOTAL = value;
					this.SendPropertyChanged("TOTAL");
					this.OnTOTALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NET", DbType="Decimal(15,2) NOT NULL")]
		public decimal NET
		{
			get
			{
				return this._NET;
			}
			set
			{
				if ((this._NET != value))
				{
					this.OnNETChanging(value);
					this.SendPropertyChanging();
					this._NET = value;
					this.SendPropertyChanged("NET");
					this.OnNETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VAL", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> VAL
		{
			get
			{
				return this._VAL;
			}
			set
			{
				if ((this._VAL != value))
				{
					this.OnVALChanging(value);
					this.SendPropertyChanging();
					this._VAL = value;
					this.SendPropertyChanged("VAL");
					this.OnVALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POINT", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> POINT
		{
			get
			{
				return this._POINT;
			}
			set
			{
				if ((this._POINT != value))
				{
					this.OnPOINTChanging(value);
					this.SendPropertyChanging();
					this._POINT = value;
					this.SendPropertyChanged("POINT");
					this.OnPOINTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRCODE", DbType="VarChar(20)")]
		public string PRCODE
		{
			get
			{
				return this._PRCODE;
			}
			set
			{
				if ((this._PRCODE != value))
				{
					this.OnPRCODEChanging(value);
					this.SendPropertyChanging();
					this._PRCODE = value;
					this.SendPropertyChanged("PRCODE");
					this.OnPRCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OFFERID", DbType="Int")]
		public System.Nullable<int> OFFERID
		{
			get
			{
				return this._OFFERID;
			}
			set
			{
				if ((this._OFFERID != value))
				{
					this.OnOFFERIDChanging(value);
					this.SendPropertyChanging();
					this._OFFERID = value;
					this.SendPropertyChanged("OFFERID");
					this.OnOFFERIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEMAU", DbType="VarChar(1)")]
		public string ITEMAU
		{
			get
			{
				return this._ITEMAU;
			}
			set
			{
				if ((this._ITEMAU != value))
				{
					this.OnITEMAUChanging(value);
					this.SendPropertyChanging();
					this._ITEMAU = value;
					this.SendPropertyChanged("ITEMAU");
					this.OnITEMAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEMRF", DbType="Int")]
		public System.Nullable<int> ITEMRF
		{
			get
			{
				return this._ITEMRF;
			}
			set
			{
				if ((this._ITEMRF != value))
				{
					this.OnITEMRFChanging(value);
					this.SendPropertyChanging();
					this._ITEMRF = value;
					this.SendPropertyChanged("ITEMRF");
					this.OnITEMRFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTY_RF", DbType="Decimal(15,4)")]
		public System.Nullable<decimal> QTY_RF
		{
			get
			{
				return this._QTY_RF;
			}
			set
			{
				if ((this._QTY_RF != value))
				{
					this.OnQTY_RFChanging(value);
					this.SendPropertyChanging();
					this._QTY_RF = value;
					this.SendPropertyChanged("QTY_RF");
					this.OnQTY_RFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_TOTAL", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> PR_TOTAL
		{
			get
			{
				return this._PR_TOTAL;
			}
			set
			{
				if ((this._PR_TOTAL != value))
				{
					this.OnPR_TOTALChanging(value);
					this.SendPropertyChanging();
					this._PR_TOTAL = value;
					this.SendPropertyChanged("PR_TOTAL");
					this.OnPR_TOTALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_NET", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> PR_NET
		{
			get
			{
				return this._PR_NET;
			}
			set
			{
				if ((this._PR_NET != value))
				{
					this.OnPR_NETChanging(value);
					this.SendPropertyChanging();
					this._PR_NET = value;
					this.SendPropertyChanged("PR_NET");
					this.OnPR_NETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PR_VAL", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> PR_VAL
		{
			get
			{
				return this._PR_VAL;
			}
			set
			{
				if ((this._PR_VAL != value))
				{
					this.OnPR_VALChanging(value);
					this.SendPropertyChanging();
					this._PR_VAL = value;
					this.SendPropertyChanged("PR_VAL");
					this.OnPR_VALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIVOIDED", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string PIVOIDED
		{
			get
			{
				return this._PIVOIDED;
			}
			set
			{
				if ((this._PIVOIDED != value))
				{
					this.OnPIVOIDEDChanging(value);
					this.SendPropertyChanging();
					this._PIVOIDED = value;
					this.SendPropertyChanged("PIVOIDED");
					this.OnPIVOIDEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PISTATUS", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string PISTATUS
		{
			get
			{
				return this._PISTATUS;
			}
			set
			{
				if ((this._PISTATUS != value))
				{
					this.OnPISTATUSChanging(value);
					this.SendPropertyChanging();
					this._PISTATUS = value;
					this.SendPropertyChanged("PISTATUS");
					this.OnPISTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORKDATE", DbType="DateTime NOT NULL")]
		public System.DateTime WORKDATE
		{
			get
			{
				return this._WORKDATE;
			}
			set
			{
				if ((this._WORKDATE != value))
				{
					this.OnWORKDATEChanging(value);
					this.SendPropertyChanging();
					this._WORKDATE = value;
					this.SendPropertyChanged("WORKDATE");
					this.OnWORKDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAG_F", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> TAG_F
		{
			get
			{
				return this._TAG_F;
			}
			set
			{
				if ((this._TAG_F != value))
				{
					this.OnTAG_FChanging(value);
					this.SendPropertyChanging();
					this._TAG_F = value;
					this.SendPropertyChanged("TAG_F");
					this.OnTAG_FChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAG_S", DbType="VarChar(10)")]
		public string TAG_S
		{
			get
			{
				return this._TAG_S;
			}
			set
			{
				if ((this._TAG_S != value))
				{
					this.OnTAG_SChanging(value);
					this.SendPropertyChanging();
					this._TAG_S = value;
					this.SendPropertyChanged("TAG_S");
					this.OnTAG_SChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="POS_PT_POS_PI", Storage="_POS_PT", ThisKey="WH_ID,TMCODE,ABBNO,PTDATE", OtherKey="WH_ID,TMCODE,ABBNO,PTDATE", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public POS_PT POS_PT
		{
			get
			{
				return this._POS_PT.Entity;
			}
			set
			{
				POS_PT previousValue = this._POS_PT.Entity;
				if (((previousValue != value) 
							|| (this._POS_PT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._POS_PT.Entity = null;
						previousValue.POS_PIs.Remove(this);
					}
					this._POS_PT.Entity = value;
					if ((value != null))
					{
						value.POS_PIs.Add(this);
						this._WH_ID = value.WH_ID;
						this._TMCODE = value.TMCODE;
						this._ABBNO = value.ABBNO;
						this._PTDATE = value.PTDATE;
					}
					else
					{
						this._WH_ID = default(int);
						this._TMCODE = default(string);
						this._ABBNO = default(string);
						this._PTDATE = default(System.DateTime);
					}
					this.SendPropertyChanged("POS_PT");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.POS_PT")]
	public partial class POS_PT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _WH_ID;
		
		private string _TMCODE;
		
		private string _ABBNO;
		
		private System.DateTime _PTDATE;
		
		private System.DateTime _PTTIME;
		
		private short _SHIFTNO;
		
		private string _PTSTATUS;
		
		private string _OCSTATUS;
		
		private System.DateTime _WORKDATE;
		
		private int _ST_ID_LOG;
		
		private int _ST_ID;
		
		private string _IV_DOCNO;
		
		private string _CN_DOCNO;
		
		private string _REFNO;
		
		private string _CT_ID;
		
		private string _CT_BILL_TO;
		
		private string _CT_BILL_ADDR1;
		
		private string _CT_BILL_ADDR2;
		
		private string _CT_BILL_ADDR3;
		
		private string _CT_CARDID;
		
		private string _CTTYPE;
		
		private string _CTCAT;
		
		private System.Nullable<int> _CO_ID;
		
		private string _CO_CARDID;
		
		private System.Nullable<decimal> _POINT;
		
		private System.Nullable<decimal> _POINT_TOTAL;
		
		private string _SDPCODE;
		
		private string _PRCODE;
		
		private string _REMARK;
		
		private string _VATTYPE;
		
		private decimal _VATRATE;
		
		private decimal _QTY;
		
		private decimal _SUMMARY;
		
		private decimal _ITEMDISCOUNT;
		
		private decimal _SUBTOTAL;
		
		private decimal _SUBTOTAL_NORM;
		
		private string _DISCOUNTSTR;
		
		private decimal _DISCOUNTAMT;
		
		private decimal _DISCOUNTAMT_VAT;
		
		private decimal _TOTAL;
		
		private decimal _TOTAL_VAT;
		
		private decimal _VATAMT;
		
		private decimal _ROUNDAMT;
		
		private decimal _NET;
		
		private System.Nullable<decimal> _VAL;
		
		private System.Nullable<decimal> _PAY_OTHER;
		
		private System.Nullable<decimal> _PAY_CASH;
		
		private System.Nullable<decimal> _PAY_CASH_TENDER;
		
		private System.Nullable<decimal> _PAY_CARD1;
		
		private System.Nullable<int> _PAY_CARD_CD_ID1;
		
		private string _PAY_CARD_ID1;
		
		private string _PAY_CARD_NAME1;
		
		private System.Nullable<decimal> _PAY_CARD2;
		
		private System.Nullable<int> _PAY_CARD_CD_ID2;
		
		private string _PAY_CARD_ID2;
		
		private string _PAY_CARD_NAME2;
		
		private string _RF_IV_DOCNO;
		
		private System.Nullable<decimal> _RF_IV_RMVALUE;
		
		private System.Nullable<decimal> _RF_RIGHTAMT;
		
		private System.Nullable<decimal> _RF_DIFAMT;
		
		private System.Nullable<decimal> _TAG_F;
		
		private string _TAG_S;
		
		private EntitySet<POS_PI> _POS_PIs;
		
		private EntitySet<POS_PT_PR> _POS_PT_PRs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWH_IDChanging(int value);
    partial void OnWH_IDChanged();
    partial void OnTMCODEChanging(string value);
    partial void OnTMCODEChanged();
    partial void OnABBNOChanging(string value);
    partial void OnABBNOChanged();
    partial void OnPTDATEChanging(System.DateTime value);
    partial void OnPTDATEChanged();
    partial void OnPTTIMEChanging(System.DateTime value);
    partial void OnPTTIMEChanged();
    partial void OnSHIFTNOChanging(short value);
    partial void OnSHIFTNOChanged();
    partial void OnPTSTATUSChanging(string value);
    partial void OnPTSTATUSChanged();
    partial void OnOCSTATUSChanging(string value);
    partial void OnOCSTATUSChanged();
    partial void OnWORKDATEChanging(System.DateTime value);
    partial void OnWORKDATEChanged();
    partial void OnST_ID_LOGChanging(int value);
    partial void OnST_ID_LOGChanged();
    partial void OnST_IDChanging(int value);
    partial void OnST_IDChanged();
    partial void OnIV_DOCNOChanging(string value);
    partial void OnIV_DOCNOChanged();
    partial void OnCN_DOCNOChanging(string value);
    partial void OnCN_DOCNOChanged();
    partial void OnREFNOChanging(string value);
    partial void OnREFNOChanged();
    partial void OnCT_IDChanging(string value);
    partial void OnCT_IDChanged();
    partial void OnCT_BILL_TOChanging(string value);
    partial void OnCT_BILL_TOChanged();
    partial void OnCT_BILL_ADDR1Changing(string value);
    partial void OnCT_BILL_ADDR1Changed();
    partial void OnCT_BILL_ADDR2Changing(string value);
    partial void OnCT_BILL_ADDR2Changed();
    partial void OnCT_BILL_ADDR3Changing(string value);
    partial void OnCT_BILL_ADDR3Changed();
    partial void OnCT_CARDIDChanging(string value);
    partial void OnCT_CARDIDChanged();
    partial void OnCTTYPEChanging(string value);
    partial void OnCTTYPEChanged();
    partial void OnCTCATChanging(string value);
    partial void OnCTCATChanged();
    partial void OnCO_IDChanging(System.Nullable<int> value);
    partial void OnCO_IDChanged();
    partial void OnCO_CARDIDChanging(string value);
    partial void OnCO_CARDIDChanged();
    partial void OnPOINTChanging(System.Nullable<decimal> value);
    partial void OnPOINTChanged();
    partial void OnPOINT_TOTALChanging(System.Nullable<decimal> value);
    partial void OnPOINT_TOTALChanged();
    partial void OnSDPCODEChanging(string value);
    partial void OnSDPCODEChanged();
    partial void OnPRCODEChanging(string value);
    partial void OnPRCODEChanged();
    partial void OnREMARKChanging(string value);
    partial void OnREMARKChanged();
    partial void OnVATTYPEChanging(string value);
    partial void OnVATTYPEChanged();
    partial void OnVATRATEChanging(decimal value);
    partial void OnVATRATEChanged();
    partial void OnQTYChanging(decimal value);
    partial void OnQTYChanged();
    partial void OnSUMMARYChanging(decimal value);
    partial void OnSUMMARYChanged();
    partial void OnITEMDISCOUNTChanging(decimal value);
    partial void OnITEMDISCOUNTChanged();
    partial void OnSUBTOTALChanging(decimal value);
    partial void OnSUBTOTALChanged();
    partial void OnSUBTOTAL_NORMChanging(decimal value);
    partial void OnSUBTOTAL_NORMChanged();
    partial void OnDISCOUNTSTRChanging(string value);
    partial void OnDISCOUNTSTRChanged();
    partial void OnDISCOUNTAMTChanging(decimal value);
    partial void OnDISCOUNTAMTChanged();
    partial void OnDISCOUNTAMT_VATChanging(decimal value);
    partial void OnDISCOUNTAMT_VATChanged();
    partial void OnTOTALChanging(decimal value);
    partial void OnTOTALChanged();
    partial void OnTOTAL_VATChanging(decimal value);
    partial void OnTOTAL_VATChanged();
    partial void OnVATAMTChanging(decimal value);
    partial void OnVATAMTChanged();
    partial void OnROUNDAMTChanging(decimal value);
    partial void OnROUNDAMTChanged();
    partial void OnNETChanging(decimal value);
    partial void OnNETChanged();
    partial void OnVALChanging(System.Nullable<decimal> value);
    partial void OnVALChanged();
    partial void OnPAY_OTHERChanging(System.Nullable<decimal> value);
    partial void OnPAY_OTHERChanged();
    partial void OnPAY_CASHChanging(System.Nullable<decimal> value);
    partial void OnPAY_CASHChanged();
    partial void OnPAY_CASH_TENDERChanging(System.Nullable<decimal> value);
    partial void OnPAY_CASH_TENDERChanged();
    partial void OnPAY_CARD1Changing(System.Nullable<decimal> value);
    partial void OnPAY_CARD1Changed();
    partial void OnPAY_CARD_CD_ID1Changing(System.Nullable<int> value);
    partial void OnPAY_CARD_CD_ID1Changed();
    partial void OnPAY_CARD_ID1Changing(string value);
    partial void OnPAY_CARD_ID1Changed();
    partial void OnPAY_CARD_NAME1Changing(string value);
    partial void OnPAY_CARD_NAME1Changed();
    partial void OnPAY_CARD2Changing(System.Nullable<decimal> value);
    partial void OnPAY_CARD2Changed();
    partial void OnPAY_CARD_CD_ID2Changing(System.Nullable<int> value);
    partial void OnPAY_CARD_CD_ID2Changed();
    partial void OnPAY_CARD_ID2Changing(string value);
    partial void OnPAY_CARD_ID2Changed();
    partial void OnPAY_CARD_NAME2Changing(string value);
    partial void OnPAY_CARD_NAME2Changed();
    partial void OnRF_IV_DOCNOChanging(string value);
    partial void OnRF_IV_DOCNOChanged();
    partial void OnRF_IV_RMVALUEChanging(System.Nullable<decimal> value);
    partial void OnRF_IV_RMVALUEChanged();
    partial void OnRF_RIGHTAMTChanging(System.Nullable<decimal> value);
    partial void OnRF_RIGHTAMTChanged();
    partial void OnRF_DIFAMTChanging(System.Nullable<decimal> value);
    partial void OnRF_DIFAMTChanged();
    partial void OnTAG_FChanging(System.Nullable<decimal> value);
    partial void OnTAG_FChanged();
    partial void OnTAG_SChanging(string value);
    partial void OnTAG_SChanged();
    #endregion
		
		public POS_PT()
		{
			this._POS_PIs = new EntitySet<POS_PI>(new Action<POS_PI>(this.attach_POS_PIs), new Action<POS_PI>(this.detach_POS_PIs));
			this._POS_PT_PRs = new EntitySet<POS_PT_PR>(new Action<POS_PT_PR>(this.attach_POS_PT_PRs), new Action<POS_PT_PR>(this.detach_POS_PT_PRs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WH_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int WH_ID
		{
			get
			{
				return this._WH_ID;
			}
			set
			{
				if ((this._WH_ID != value))
				{
					this.OnWH_IDChanging(value);
					this.SendPropertyChanging();
					this._WH_ID = value;
					this.SendPropertyChanged("WH_ID");
					this.OnWH_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TMCODE", DbType="VarChar(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TMCODE
		{
			get
			{
				return this._TMCODE;
			}
			set
			{
				if ((this._TMCODE != value))
				{
					this.OnTMCODEChanging(value);
					this.SendPropertyChanging();
					this._TMCODE = value;
					this.SendPropertyChanged("TMCODE");
					this.OnTMCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ABBNO", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ABBNO
		{
			get
			{
				return this._ABBNO;
			}
			set
			{
				if ((this._ABBNO != value))
				{
					this.OnABBNOChanging(value);
					this.SendPropertyChanging();
					this._ABBNO = value;
					this.SendPropertyChanged("ABBNO");
					this.OnABBNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PTDATE", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime PTDATE
		{
			get
			{
				return this._PTDATE;
			}
			set
			{
				if ((this._PTDATE != value))
				{
					this.OnPTDATEChanging(value);
					this.SendPropertyChanging();
					this._PTDATE = value;
					this.SendPropertyChanged("PTDATE");
					this.OnPTDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PTTIME", DbType="DateTime NOT NULL")]
		public System.DateTime PTTIME
		{
			get
			{
				return this._PTTIME;
			}
			set
			{
				if ((this._PTTIME != value))
				{
					this.OnPTTIMEChanging(value);
					this.SendPropertyChanging();
					this._PTTIME = value;
					this.SendPropertyChanged("PTTIME");
					this.OnPTTIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHIFTNO", DbType="SmallInt NOT NULL")]
		public short SHIFTNO
		{
			get
			{
				return this._SHIFTNO;
			}
			set
			{
				if ((this._SHIFTNO != value))
				{
					this.OnSHIFTNOChanging(value);
					this.SendPropertyChanging();
					this._SHIFTNO = value;
					this.SendPropertyChanged("SHIFTNO");
					this.OnSHIFTNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PTSTATUS", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string PTSTATUS
		{
			get
			{
				return this._PTSTATUS;
			}
			set
			{
				if ((this._PTSTATUS != value))
				{
					this.OnPTSTATUSChanging(value);
					this.SendPropertyChanging();
					this._PTSTATUS = value;
					this.SendPropertyChanged("PTSTATUS");
					this.OnPTSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OCSTATUS", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string OCSTATUS
		{
			get
			{
				return this._OCSTATUS;
			}
			set
			{
				if ((this._OCSTATUS != value))
				{
					this.OnOCSTATUSChanging(value);
					this.SendPropertyChanging();
					this._OCSTATUS = value;
					this.SendPropertyChanged("OCSTATUS");
					this.OnOCSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORKDATE", DbType="DateTime NOT NULL")]
		public System.DateTime WORKDATE
		{
			get
			{
				return this._WORKDATE;
			}
			set
			{
				if ((this._WORKDATE != value))
				{
					this.OnWORKDATEChanging(value);
					this.SendPropertyChanging();
					this._WORKDATE = value;
					this.SendPropertyChanged("WORKDATE");
					this.OnWORKDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_ID_LOG", DbType="Int NOT NULL")]
		public int ST_ID_LOG
		{
			get
			{
				return this._ST_ID_LOG;
			}
			set
			{
				if ((this._ST_ID_LOG != value))
				{
					this.OnST_ID_LOGChanging(value);
					this.SendPropertyChanging();
					this._ST_ID_LOG = value;
					this.SendPropertyChanged("ST_ID_LOG");
					this.OnST_ID_LOGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_ID", DbType="Int NOT NULL")]
		public int ST_ID
		{
			get
			{
				return this._ST_ID;
			}
			set
			{
				if ((this._ST_ID != value))
				{
					this.OnST_IDChanging(value);
					this.SendPropertyChanging();
					this._ST_ID = value;
					this.SendPropertyChanged("ST_ID");
					this.OnST_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IV_DOCNO", DbType="VarChar(20)")]
		public string IV_DOCNO
		{
			get
			{
				return this._IV_DOCNO;
			}
			set
			{
				if ((this._IV_DOCNO != value))
				{
					this.OnIV_DOCNOChanging(value);
					this.SendPropertyChanging();
					this._IV_DOCNO = value;
					this.SendPropertyChanged("IV_DOCNO");
					this.OnIV_DOCNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CN_DOCNO", DbType="VarChar(20)")]
		public string CN_DOCNO
		{
			get
			{
				return this._CN_DOCNO;
			}
			set
			{
				if ((this._CN_DOCNO != value))
				{
					this.OnCN_DOCNOChanging(value);
					this.SendPropertyChanging();
					this._CN_DOCNO = value;
					this.SendPropertyChanged("CN_DOCNO");
					this.OnCN_DOCNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REFNO", DbType="VarChar(20)")]
		public string REFNO
		{
			get
			{
				return this._REFNO;
			}
			set
			{
				if ((this._REFNO != value))
				{
					this.OnREFNOChanging(value);
					this.SendPropertyChanging();
					this._REFNO = value;
					this.SendPropertyChanged("REFNO");
					this.OnREFNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CT_ID", DbType="VarChar(20)")]
		public string CT_ID
		{
			get
			{
				return this._CT_ID;
			}
			set
			{
				if ((this._CT_ID != value))
				{
					this.OnCT_IDChanging(value);
					this.SendPropertyChanging();
					this._CT_ID = value;
					this.SendPropertyChanged("CT_ID");
					this.OnCT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CT_BILL_TO", DbType="VarChar(100)")]
		public string CT_BILL_TO
		{
			get
			{
				return this._CT_BILL_TO;
			}
			set
			{
				if ((this._CT_BILL_TO != value))
				{
					this.OnCT_BILL_TOChanging(value);
					this.SendPropertyChanging();
					this._CT_BILL_TO = value;
					this.SendPropertyChanged("CT_BILL_TO");
					this.OnCT_BILL_TOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CT_BILL_ADDR1", DbType="VarChar(100)")]
		public string CT_BILL_ADDR1
		{
			get
			{
				return this._CT_BILL_ADDR1;
			}
			set
			{
				if ((this._CT_BILL_ADDR1 != value))
				{
					this.OnCT_BILL_ADDR1Changing(value);
					this.SendPropertyChanging();
					this._CT_BILL_ADDR1 = value;
					this.SendPropertyChanged("CT_BILL_ADDR1");
					this.OnCT_BILL_ADDR1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CT_BILL_ADDR2", DbType="VarChar(100)")]
		public string CT_BILL_ADDR2
		{
			get
			{
				return this._CT_BILL_ADDR2;
			}
			set
			{
				if ((this._CT_BILL_ADDR2 != value))
				{
					this.OnCT_BILL_ADDR2Changing(value);
					this.SendPropertyChanging();
					this._CT_BILL_ADDR2 = value;
					this.SendPropertyChanged("CT_BILL_ADDR2");
					this.OnCT_BILL_ADDR2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CT_BILL_ADDR3", DbType="VarChar(100)")]
		public string CT_BILL_ADDR3
		{
			get
			{
				return this._CT_BILL_ADDR3;
			}
			set
			{
				if ((this._CT_BILL_ADDR3 != value))
				{
					this.OnCT_BILL_ADDR3Changing(value);
					this.SendPropertyChanging();
					this._CT_BILL_ADDR3 = value;
					this.SendPropertyChanged("CT_BILL_ADDR3");
					this.OnCT_BILL_ADDR3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CT_CARDID", DbType="VarChar(20)")]
		public string CT_CARDID
		{
			get
			{
				return this._CT_CARDID;
			}
			set
			{
				if ((this._CT_CARDID != value))
				{
					this.OnCT_CARDIDChanging(value);
					this.SendPropertyChanging();
					this._CT_CARDID = value;
					this.SendPropertyChanged("CT_CARDID");
					this.OnCT_CARDIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTTYPE", DbType="VarChar(1)")]
		public string CTTYPE
		{
			get
			{
				return this._CTTYPE;
			}
			set
			{
				if ((this._CTTYPE != value))
				{
					this.OnCTTYPEChanging(value);
					this.SendPropertyChanging();
					this._CTTYPE = value;
					this.SendPropertyChanged("CTTYPE");
					this.OnCTTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTCAT", DbType="VarChar(3)")]
		public string CTCAT
		{
			get
			{
				return this._CTCAT;
			}
			set
			{
				if ((this._CTCAT != value))
				{
					this.OnCTCATChanging(value);
					this.SendPropertyChanging();
					this._CTCAT = value;
					this.SendPropertyChanged("CTCAT");
					this.OnCTCATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CO_ID", DbType="Int")]
		public System.Nullable<int> CO_ID
		{
			get
			{
				return this._CO_ID;
			}
			set
			{
				if ((this._CO_ID != value))
				{
					this.OnCO_IDChanging(value);
					this.SendPropertyChanging();
					this._CO_ID = value;
					this.SendPropertyChanged("CO_ID");
					this.OnCO_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CO_CARDID", DbType="VarChar(20)")]
		public string CO_CARDID
		{
			get
			{
				return this._CO_CARDID;
			}
			set
			{
				if ((this._CO_CARDID != value))
				{
					this.OnCO_CARDIDChanging(value);
					this.SendPropertyChanging();
					this._CO_CARDID = value;
					this.SendPropertyChanged("CO_CARDID");
					this.OnCO_CARDIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POINT", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> POINT
		{
			get
			{
				return this._POINT;
			}
			set
			{
				if ((this._POINT != value))
				{
					this.OnPOINTChanging(value);
					this.SendPropertyChanging();
					this._POINT = value;
					this.SendPropertyChanged("POINT");
					this.OnPOINTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POINT_TOTAL", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> POINT_TOTAL
		{
			get
			{
				return this._POINT_TOTAL;
			}
			set
			{
				if ((this._POINT_TOTAL != value))
				{
					this.OnPOINT_TOTALChanging(value);
					this.SendPropertyChanging();
					this._POINT_TOTAL = value;
					this.SendPropertyChanged("POINT_TOTAL");
					this.OnPOINT_TOTALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDPCODE", DbType="VarChar(20)")]
		public string SDPCODE
		{
			get
			{
				return this._SDPCODE;
			}
			set
			{
				if ((this._SDPCODE != value))
				{
					this.OnSDPCODEChanging(value);
					this.SendPropertyChanging();
					this._SDPCODE = value;
					this.SendPropertyChanged("SDPCODE");
					this.OnSDPCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRCODE", DbType="VarChar(20)")]
		public string PRCODE
		{
			get
			{
				return this._PRCODE;
			}
			set
			{
				if ((this._PRCODE != value))
				{
					this.OnPRCODEChanging(value);
					this.SendPropertyChanging();
					this._PRCODE = value;
					this.SendPropertyChanged("PRCODE");
					this.OnPRCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REMARK", DbType="VarChar(40)")]
		public string REMARK
		{
			get
			{
				return this._REMARK;
			}
			set
			{
				if ((this._REMARK != value))
				{
					this.OnREMARKChanging(value);
					this.SendPropertyChanging();
					this._REMARK = value;
					this.SendPropertyChanged("REMARK");
					this.OnREMARKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VATTYPE", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string VATTYPE
		{
			get
			{
				return this._VATTYPE;
			}
			set
			{
				if ((this._VATTYPE != value))
				{
					this.OnVATTYPEChanging(value);
					this.SendPropertyChanging();
					this._VATTYPE = value;
					this.SendPropertyChanged("VATTYPE");
					this.OnVATTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VATRATE", DbType="Decimal(15,2) NOT NULL")]
		public decimal VATRATE
		{
			get
			{
				return this._VATRATE;
			}
			set
			{
				if ((this._VATRATE != value))
				{
					this.OnVATRATEChanging(value);
					this.SendPropertyChanging();
					this._VATRATE = value;
					this.SendPropertyChanged("VATRATE");
					this.OnVATRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTY", DbType="Decimal(15,4) NOT NULL")]
		public decimal QTY
		{
			get
			{
				return this._QTY;
			}
			set
			{
				if ((this._QTY != value))
				{
					this.OnQTYChanging(value);
					this.SendPropertyChanging();
					this._QTY = value;
					this.SendPropertyChanged("QTY");
					this.OnQTYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUMMARY", DbType="Decimal(15,2) NOT NULL")]
		public decimal SUMMARY
		{
			get
			{
				return this._SUMMARY;
			}
			set
			{
				if ((this._SUMMARY != value))
				{
					this.OnSUMMARYChanging(value);
					this.SendPropertyChanging();
					this._SUMMARY = value;
					this.SendPropertyChanged("SUMMARY");
					this.OnSUMMARYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEMDISCOUNT", DbType="Decimal(15,2) NOT NULL")]
		public decimal ITEMDISCOUNT
		{
			get
			{
				return this._ITEMDISCOUNT;
			}
			set
			{
				if ((this._ITEMDISCOUNT != value))
				{
					this.OnITEMDISCOUNTChanging(value);
					this.SendPropertyChanging();
					this._ITEMDISCOUNT = value;
					this.SendPropertyChanged("ITEMDISCOUNT");
					this.OnITEMDISCOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBTOTAL", DbType="Decimal(15,2) NOT NULL")]
		public decimal SUBTOTAL
		{
			get
			{
				return this._SUBTOTAL;
			}
			set
			{
				if ((this._SUBTOTAL != value))
				{
					this.OnSUBTOTALChanging(value);
					this.SendPropertyChanging();
					this._SUBTOTAL = value;
					this.SendPropertyChanged("SUBTOTAL");
					this.OnSUBTOTALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBTOTAL_NORM", DbType="Decimal(15,2) NOT NULL")]
		public decimal SUBTOTAL_NORM
		{
			get
			{
				return this._SUBTOTAL_NORM;
			}
			set
			{
				if ((this._SUBTOTAL_NORM != value))
				{
					this.OnSUBTOTAL_NORMChanging(value);
					this.SendPropertyChanging();
					this._SUBTOTAL_NORM = value;
					this.SendPropertyChanged("SUBTOTAL_NORM");
					this.OnSUBTOTAL_NORMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISCOUNTSTR", DbType="VarChar(80)")]
		public string DISCOUNTSTR
		{
			get
			{
				return this._DISCOUNTSTR;
			}
			set
			{
				if ((this._DISCOUNTSTR != value))
				{
					this.OnDISCOUNTSTRChanging(value);
					this.SendPropertyChanging();
					this._DISCOUNTSTR = value;
					this.SendPropertyChanged("DISCOUNTSTR");
					this.OnDISCOUNTSTRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISCOUNTAMT", DbType="Decimal(15,2) NOT NULL")]
		public decimal DISCOUNTAMT
		{
			get
			{
				return this._DISCOUNTAMT;
			}
			set
			{
				if ((this._DISCOUNTAMT != value))
				{
					this.OnDISCOUNTAMTChanging(value);
					this.SendPropertyChanging();
					this._DISCOUNTAMT = value;
					this.SendPropertyChanged("DISCOUNTAMT");
					this.OnDISCOUNTAMTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISCOUNTAMT_VAT", DbType="Decimal(15,2) NOT NULL")]
		public decimal DISCOUNTAMT_VAT
		{
			get
			{
				return this._DISCOUNTAMT_VAT;
			}
			set
			{
				if ((this._DISCOUNTAMT_VAT != value))
				{
					this.OnDISCOUNTAMT_VATChanging(value);
					this.SendPropertyChanging();
					this._DISCOUNTAMT_VAT = value;
					this.SendPropertyChanged("DISCOUNTAMT_VAT");
					this.OnDISCOUNTAMT_VATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL", DbType="Decimal(15,2) NOT NULL")]
		public decimal TOTAL
		{
			get
			{
				return this._TOTAL;
			}
			set
			{
				if ((this._TOTAL != value))
				{
					this.OnTOTALChanging(value);
					this.SendPropertyChanging();
					this._TOTAL = value;
					this.SendPropertyChanged("TOTAL");
					this.OnTOTALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_VAT", DbType="Decimal(15,2) NOT NULL")]
		public decimal TOTAL_VAT
		{
			get
			{
				return this._TOTAL_VAT;
			}
			set
			{
				if ((this._TOTAL_VAT != value))
				{
					this.OnTOTAL_VATChanging(value);
					this.SendPropertyChanging();
					this._TOTAL_VAT = value;
					this.SendPropertyChanged("TOTAL_VAT");
					this.OnTOTAL_VATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VATAMT", DbType="Decimal(15,2) NOT NULL")]
		public decimal VATAMT
		{
			get
			{
				return this._VATAMT;
			}
			set
			{
				if ((this._VATAMT != value))
				{
					this.OnVATAMTChanging(value);
					this.SendPropertyChanging();
					this._VATAMT = value;
					this.SendPropertyChanged("VATAMT");
					this.OnVATAMTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROUNDAMT", DbType="Decimal(15,2) NOT NULL")]
		public decimal ROUNDAMT
		{
			get
			{
				return this._ROUNDAMT;
			}
			set
			{
				if ((this._ROUNDAMT != value))
				{
					this.OnROUNDAMTChanging(value);
					this.SendPropertyChanging();
					this._ROUNDAMT = value;
					this.SendPropertyChanged("ROUNDAMT");
					this.OnROUNDAMTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NET", DbType="Decimal(15,2) NOT NULL")]
		public decimal NET
		{
			get
			{
				return this._NET;
			}
			set
			{
				if ((this._NET != value))
				{
					this.OnNETChanging(value);
					this.SendPropertyChanging();
					this._NET = value;
					this.SendPropertyChanged("NET");
					this.OnNETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VAL", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> VAL
		{
			get
			{
				return this._VAL;
			}
			set
			{
				if ((this._VAL != value))
				{
					this.OnVALChanging(value);
					this.SendPropertyChanging();
					this._VAL = value;
					this.SendPropertyChanged("VAL");
					this.OnVALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAY_OTHER", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> PAY_OTHER
		{
			get
			{
				return this._PAY_OTHER;
			}
			set
			{
				if ((this._PAY_OTHER != value))
				{
					this.OnPAY_OTHERChanging(value);
					this.SendPropertyChanging();
					this._PAY_OTHER = value;
					this.SendPropertyChanged("PAY_OTHER");
					this.OnPAY_OTHERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAY_CASH", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> PAY_CASH
		{
			get
			{
				return this._PAY_CASH;
			}
			set
			{
				if ((this._PAY_CASH != value))
				{
					this.OnPAY_CASHChanging(value);
					this.SendPropertyChanging();
					this._PAY_CASH = value;
					this.SendPropertyChanged("PAY_CASH");
					this.OnPAY_CASHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAY_CASH_TENDER", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> PAY_CASH_TENDER
		{
			get
			{
				return this._PAY_CASH_TENDER;
			}
			set
			{
				if ((this._PAY_CASH_TENDER != value))
				{
					this.OnPAY_CASH_TENDERChanging(value);
					this.SendPropertyChanging();
					this._PAY_CASH_TENDER = value;
					this.SendPropertyChanged("PAY_CASH_TENDER");
					this.OnPAY_CASH_TENDERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAY_CARD1", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> PAY_CARD1
		{
			get
			{
				return this._PAY_CARD1;
			}
			set
			{
				if ((this._PAY_CARD1 != value))
				{
					this.OnPAY_CARD1Changing(value);
					this.SendPropertyChanging();
					this._PAY_CARD1 = value;
					this.SendPropertyChanged("PAY_CARD1");
					this.OnPAY_CARD1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAY_CARD_CD_ID1", DbType="Int")]
		public System.Nullable<int> PAY_CARD_CD_ID1
		{
			get
			{
				return this._PAY_CARD_CD_ID1;
			}
			set
			{
				if ((this._PAY_CARD_CD_ID1 != value))
				{
					this.OnPAY_CARD_CD_ID1Changing(value);
					this.SendPropertyChanging();
					this._PAY_CARD_CD_ID1 = value;
					this.SendPropertyChanged("PAY_CARD_CD_ID1");
					this.OnPAY_CARD_CD_ID1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAY_CARD_ID1", DbType="VarChar(20)")]
		public string PAY_CARD_ID1
		{
			get
			{
				return this._PAY_CARD_ID1;
			}
			set
			{
				if ((this._PAY_CARD_ID1 != value))
				{
					this.OnPAY_CARD_ID1Changing(value);
					this.SendPropertyChanging();
					this._PAY_CARD_ID1 = value;
					this.SendPropertyChanged("PAY_CARD_ID1");
					this.OnPAY_CARD_ID1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAY_CARD_NAME1", DbType="VarChar(60)")]
		public string PAY_CARD_NAME1
		{
			get
			{
				return this._PAY_CARD_NAME1;
			}
			set
			{
				if ((this._PAY_CARD_NAME1 != value))
				{
					this.OnPAY_CARD_NAME1Changing(value);
					this.SendPropertyChanging();
					this._PAY_CARD_NAME1 = value;
					this.SendPropertyChanged("PAY_CARD_NAME1");
					this.OnPAY_CARD_NAME1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAY_CARD2", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> PAY_CARD2
		{
			get
			{
				return this._PAY_CARD2;
			}
			set
			{
				if ((this._PAY_CARD2 != value))
				{
					this.OnPAY_CARD2Changing(value);
					this.SendPropertyChanging();
					this._PAY_CARD2 = value;
					this.SendPropertyChanged("PAY_CARD2");
					this.OnPAY_CARD2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAY_CARD_CD_ID2", DbType="Int")]
		public System.Nullable<int> PAY_CARD_CD_ID2
		{
			get
			{
				return this._PAY_CARD_CD_ID2;
			}
			set
			{
				if ((this._PAY_CARD_CD_ID2 != value))
				{
					this.OnPAY_CARD_CD_ID2Changing(value);
					this.SendPropertyChanging();
					this._PAY_CARD_CD_ID2 = value;
					this.SendPropertyChanged("PAY_CARD_CD_ID2");
					this.OnPAY_CARD_CD_ID2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAY_CARD_ID2", DbType="VarChar(20)")]
		public string PAY_CARD_ID2
		{
			get
			{
				return this._PAY_CARD_ID2;
			}
			set
			{
				if ((this._PAY_CARD_ID2 != value))
				{
					this.OnPAY_CARD_ID2Changing(value);
					this.SendPropertyChanging();
					this._PAY_CARD_ID2 = value;
					this.SendPropertyChanged("PAY_CARD_ID2");
					this.OnPAY_CARD_ID2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAY_CARD_NAME2", DbType="VarChar(60)")]
		public string PAY_CARD_NAME2
		{
			get
			{
				return this._PAY_CARD_NAME2;
			}
			set
			{
				if ((this._PAY_CARD_NAME2 != value))
				{
					this.OnPAY_CARD_NAME2Changing(value);
					this.SendPropertyChanging();
					this._PAY_CARD_NAME2 = value;
					this.SendPropertyChanged("PAY_CARD_NAME2");
					this.OnPAY_CARD_NAME2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RF_IV_DOCNO", DbType="VarChar(20)")]
		public string RF_IV_DOCNO
		{
			get
			{
				return this._RF_IV_DOCNO;
			}
			set
			{
				if ((this._RF_IV_DOCNO != value))
				{
					this.OnRF_IV_DOCNOChanging(value);
					this.SendPropertyChanging();
					this._RF_IV_DOCNO = value;
					this.SendPropertyChanged("RF_IV_DOCNO");
					this.OnRF_IV_DOCNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RF_IV_RMVALUE", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> RF_IV_RMVALUE
		{
			get
			{
				return this._RF_IV_RMVALUE;
			}
			set
			{
				if ((this._RF_IV_RMVALUE != value))
				{
					this.OnRF_IV_RMVALUEChanging(value);
					this.SendPropertyChanging();
					this._RF_IV_RMVALUE = value;
					this.SendPropertyChanged("RF_IV_RMVALUE");
					this.OnRF_IV_RMVALUEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RF_RIGHTAMT", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> RF_RIGHTAMT
		{
			get
			{
				return this._RF_RIGHTAMT;
			}
			set
			{
				if ((this._RF_RIGHTAMT != value))
				{
					this.OnRF_RIGHTAMTChanging(value);
					this.SendPropertyChanging();
					this._RF_RIGHTAMT = value;
					this.SendPropertyChanged("RF_RIGHTAMT");
					this.OnRF_RIGHTAMTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RF_DIFAMT", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> RF_DIFAMT
		{
			get
			{
				return this._RF_DIFAMT;
			}
			set
			{
				if ((this._RF_DIFAMT != value))
				{
					this.OnRF_DIFAMTChanging(value);
					this.SendPropertyChanging();
					this._RF_DIFAMT = value;
					this.SendPropertyChanged("RF_DIFAMT");
					this.OnRF_DIFAMTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAG_F", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> TAG_F
		{
			get
			{
				return this._TAG_F;
			}
			set
			{
				if ((this._TAG_F != value))
				{
					this.OnTAG_FChanging(value);
					this.SendPropertyChanging();
					this._TAG_F = value;
					this.SendPropertyChanged("TAG_F");
					this.OnTAG_FChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAG_S", DbType="VarChar(10)")]
		public string TAG_S
		{
			get
			{
				return this._TAG_S;
			}
			set
			{
				if ((this._TAG_S != value))
				{
					this.OnTAG_SChanging(value);
					this.SendPropertyChanging();
					this._TAG_S = value;
					this.SendPropertyChanged("TAG_S");
					this.OnTAG_SChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="POS_PT_POS_PI", Storage="_POS_PIs", ThisKey="WH_ID,TMCODE,ABBNO,PTDATE", OtherKey="WH_ID,TMCODE,ABBNO,PTDATE")]
		public EntitySet<POS_PI> POS_PIs
		{
			get
			{
				return this._POS_PIs;
			}
			set
			{
				this._POS_PIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="POS_PT_POS_PT_PR", Storage="_POS_PT_PRs", ThisKey="WH_ID,TMCODE,ABBNO,PTDATE", OtherKey="WH_ID,TMCODE,ABBNO,PTDATE")]
		public EntitySet<POS_PT_PR> POS_PT_PRs
		{
			get
			{
				return this._POS_PT_PRs;
			}
			set
			{
				this._POS_PT_PRs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_POS_PIs(POS_PI entity)
		{
			this.SendPropertyChanging();
			entity.POS_PT = this;
		}
		
		private void detach_POS_PIs(POS_PI entity)
		{
			this.SendPropertyChanging();
			entity.POS_PT = null;
		}
		
		private void attach_POS_PT_PRs(POS_PT_PR entity)
		{
			this.SendPropertyChanging();
			entity.POS_PT = this;
		}
		
		private void detach_POS_PT_PRs(POS_PT_PR entity)
		{
			this.SendPropertyChanging();
			entity.POS_PT = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.POS_PT_PR")]
	public partial class POS_PT_PR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _WH_ID;
		
		private string _TMCODE;
		
		private string _ABBNO;
		
		private System.DateTime _PTDATE;
		
		private string _PRCODE;
		
		private int _ITEMNO;
		
		private System.Nullable<int> _SORTNO;
		
		private string _CVC_NO;
		
		private System.Nullable<decimal> _DVAL;
		
		private string _DTYPE;
		
		private System.Nullable<decimal> _TOTALB4DISC;
		
		private System.Nullable<decimal> _DISCOUNTAMT;
		
		private System.Nullable<System.DateTime> _WORKDATE;
		
		private EntityRef<POS_PT> _POS_PT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWH_IDChanging(int value);
    partial void OnWH_IDChanged();
    partial void OnTMCODEChanging(string value);
    partial void OnTMCODEChanged();
    partial void OnABBNOChanging(string value);
    partial void OnABBNOChanged();
    partial void OnPTDATEChanging(System.DateTime value);
    partial void OnPTDATEChanged();
    partial void OnPRCODEChanging(string value);
    partial void OnPRCODEChanged();
    partial void OnITEMNOChanging(int value);
    partial void OnITEMNOChanged();
    partial void OnSORTNOChanging(System.Nullable<int> value);
    partial void OnSORTNOChanged();
    partial void OnCVC_NOChanging(string value);
    partial void OnCVC_NOChanged();
    partial void OnDVALChanging(System.Nullable<decimal> value);
    partial void OnDVALChanged();
    partial void OnDTYPEChanging(string value);
    partial void OnDTYPEChanged();
    partial void OnTOTALB4DISCChanging(System.Nullable<decimal> value);
    partial void OnTOTALB4DISCChanged();
    partial void OnDISCOUNTAMTChanging(System.Nullable<decimal> value);
    partial void OnDISCOUNTAMTChanged();
    partial void OnWORKDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnWORKDATEChanged();
    #endregion
		
		public POS_PT_PR()
		{
			this._POS_PT = default(EntityRef<POS_PT>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WH_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int WH_ID
		{
			get
			{
				return this._WH_ID;
			}
			set
			{
				if ((this._WH_ID != value))
				{
					if (this._POS_PT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnWH_IDChanging(value);
					this.SendPropertyChanging();
					this._WH_ID = value;
					this.SendPropertyChanged("WH_ID");
					this.OnWH_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TMCODE", DbType="VarChar(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TMCODE
		{
			get
			{
				return this._TMCODE;
			}
			set
			{
				if ((this._TMCODE != value))
				{
					if (this._POS_PT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTMCODEChanging(value);
					this.SendPropertyChanging();
					this._TMCODE = value;
					this.SendPropertyChanged("TMCODE");
					this.OnTMCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ABBNO", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ABBNO
		{
			get
			{
				return this._ABBNO;
			}
			set
			{
				if ((this._ABBNO != value))
				{
					if (this._POS_PT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnABBNOChanging(value);
					this.SendPropertyChanging();
					this._ABBNO = value;
					this.SendPropertyChanged("ABBNO");
					this.OnABBNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PTDATE", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime PTDATE
		{
			get
			{
				return this._PTDATE;
			}
			set
			{
				if ((this._PTDATE != value))
				{
					if (this._POS_PT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPTDATEChanging(value);
					this.SendPropertyChanging();
					this._PTDATE = value;
					this.SendPropertyChanged("PTDATE");
					this.OnPTDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRCODE", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PRCODE
		{
			get
			{
				return this._PRCODE;
			}
			set
			{
				if ((this._PRCODE != value))
				{
					this.OnPRCODEChanging(value);
					this.SendPropertyChanging();
					this._PRCODE = value;
					this.SendPropertyChanged("PRCODE");
					this.OnPRCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITEMNO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ITEMNO
		{
			get
			{
				return this._ITEMNO;
			}
			set
			{
				if ((this._ITEMNO != value))
				{
					this.OnITEMNOChanging(value);
					this.SendPropertyChanging();
					this._ITEMNO = value;
					this.SendPropertyChanged("ITEMNO");
					this.OnITEMNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SORTNO", DbType="Int")]
		public System.Nullable<int> SORTNO
		{
			get
			{
				return this._SORTNO;
			}
			set
			{
				if ((this._SORTNO != value))
				{
					this.OnSORTNOChanging(value);
					this.SendPropertyChanging();
					this._SORTNO = value;
					this.SendPropertyChanged("SORTNO");
					this.OnSORTNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CVC_NO", DbType="VarChar(20)")]
		public string CVC_NO
		{
			get
			{
				return this._CVC_NO;
			}
			set
			{
				if ((this._CVC_NO != value))
				{
					this.OnCVC_NOChanging(value);
					this.SendPropertyChanging();
					this._CVC_NO = value;
					this.SendPropertyChanged("CVC_NO");
					this.OnCVC_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVAL", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> DVAL
		{
			get
			{
				return this._DVAL;
			}
			set
			{
				if ((this._DVAL != value))
				{
					this.OnDVALChanging(value);
					this.SendPropertyChanging();
					this._DVAL = value;
					this.SendPropertyChanged("DVAL");
					this.OnDVALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DTYPE", DbType="VarChar(1)")]
		public string DTYPE
		{
			get
			{
				return this._DTYPE;
			}
			set
			{
				if ((this._DTYPE != value))
				{
					this.OnDTYPEChanging(value);
					this.SendPropertyChanging();
					this._DTYPE = value;
					this.SendPropertyChanged("DTYPE");
					this.OnDTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTALB4DISC", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> TOTALB4DISC
		{
			get
			{
				return this._TOTALB4DISC;
			}
			set
			{
				if ((this._TOTALB4DISC != value))
				{
					this.OnTOTALB4DISCChanging(value);
					this.SendPropertyChanging();
					this._TOTALB4DISC = value;
					this.SendPropertyChanged("TOTALB4DISC");
					this.OnTOTALB4DISCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISCOUNTAMT", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> DISCOUNTAMT
		{
			get
			{
				return this._DISCOUNTAMT;
			}
			set
			{
				if ((this._DISCOUNTAMT != value))
				{
					this.OnDISCOUNTAMTChanging(value);
					this.SendPropertyChanging();
					this._DISCOUNTAMT = value;
					this.SendPropertyChanged("DISCOUNTAMT");
					this.OnDISCOUNTAMTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORKDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> WORKDATE
		{
			get
			{
				return this._WORKDATE;
			}
			set
			{
				if ((this._WORKDATE != value))
				{
					this.OnWORKDATEChanging(value);
					this.SendPropertyChanging();
					this._WORKDATE = value;
					this.SendPropertyChanged("WORKDATE");
					this.OnWORKDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="POS_PT_POS_PT_PR", Storage="_POS_PT", ThisKey="WH_ID,TMCODE,ABBNO,PTDATE", OtherKey="WH_ID,TMCODE,ABBNO,PTDATE", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public POS_PT POS_PT
		{
			get
			{
				return this._POS_PT.Entity;
			}
			set
			{
				POS_PT previousValue = this._POS_PT.Entity;
				if (((previousValue != value) 
							|| (this._POS_PT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._POS_PT.Entity = null;
						previousValue.POS_PT_PRs.Remove(this);
					}
					this._POS_PT.Entity = value;
					if ((value != null))
					{
						value.POS_PT_PRs.Add(this);
						this._WH_ID = value.WH_ID;
						this._TMCODE = value.TMCODE;
						this._ABBNO = value.ABBNO;
						this._PTDATE = value.PTDATE;
					}
					else
					{
						this._WH_ID = default(int);
						this._TMCODE = default(string);
						this._ABBNO = default(string);
						this._PTDATE = default(System.DateTime);
					}
					this.SendPropertyChanged("POS_PT");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PV_POS_UL")]
	public partial class PV_POS_UL
	{
		
		private int _WH_ID;
		
		private string _ABBNO;
		
		private System.DateTime _PTDATE;
		
		private System.DateTime _WORKDATE;
		
		private string _TMCODE;
		
		private string _UFLAG;
		
		public PV_POS_UL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WH_ID", DbType="Int NOT NULL")]
		public int WH_ID
		{
			get
			{
				return this._WH_ID;
			}
			set
			{
				if ((this._WH_ID != value))
				{
					this._WH_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ABBNO", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string ABBNO
		{
			get
			{
				return this._ABBNO;
			}
			set
			{
				if ((this._ABBNO != value))
				{
					this._ABBNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PTDATE", DbType="DateTime NOT NULL")]
		public System.DateTime PTDATE
		{
			get
			{
				return this._PTDATE;
			}
			set
			{
				if ((this._PTDATE != value))
				{
					this._PTDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORKDATE", DbType="DateTime NOT NULL")]
		public System.DateTime WORKDATE
		{
			get
			{
				return this._WORKDATE;
			}
			set
			{
				if ((this._WORKDATE != value))
				{
					this._WORKDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TMCODE", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string TMCODE
		{
			get
			{
				return this._TMCODE;
			}
			set
			{
				if ((this._TMCODE != value))
				{
					this._TMCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UFLAG", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string UFLAG
		{
			get
			{
				return this._UFLAG;
			}
			set
			{
				if ((this._UFLAG != value))
				{
					this._UFLAG = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PV_None_Sync")]
	public partial class PV_None_Sync
	{
		
		private System.Nullable<long> _rw;
		
		private string _whcode;
		
		private string _ABBNAME;
		
		private string _ABBNO;
		
		private string _TMCODE;
		
		private string _WORKDATE;
		
		private System.Nullable<decimal> _NET;
		
		private string _ptstatus;
		
		public PV_None_Sync()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rw", DbType="BigInt")]
		public System.Nullable<long> rw
		{
			get
			{
				return this._rw;
			}
			set
			{
				if ((this._rw != value))
				{
					this._rw = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_whcode", DbType="VarChar(10)")]
		public string whcode
		{
			get
			{
				return this._whcode;
			}
			set
			{
				if ((this._whcode != value))
				{
					this._whcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ABBNAME", DbType="VarChar(20)")]
		public string ABBNAME
		{
			get
			{
				return this._ABBNAME;
			}
			set
			{
				if ((this._ABBNAME != value))
				{
					this._ABBNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ABBNO", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ABBNO
		{
			get
			{
				return this._ABBNO;
			}
			set
			{
				if ((this._ABBNO != value))
				{
					this._ABBNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TMCODE", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string TMCODE
		{
			get
			{
				return this._TMCODE;
			}
			set
			{
				if ((this._TMCODE != value))
				{
					this._TMCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORKDATE", DbType="VarChar(10)")]
		public string WORKDATE
		{
			get
			{
				return this._WORKDATE;
			}
			set
			{
				if ((this._WORKDATE != value))
				{
					this._WORKDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NET", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> NET
		{
			get
			{
				return this._NET;
			}
			set
			{
				if ((this._NET != value))
				{
					this._NET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ptstatus", DbType="VarChar(9)")]
		public string ptstatus
		{
			get
			{
				return this._ptstatus;
			}
			set
			{
				if ((this._ptstatus != value))
				{
					this._ptstatus = value;
				}
			}
		}
	}
	
	public partial class PF_GET_SALESResult
	{
		
		private System.Nullable<int> _Ncnt;
		
		private System.Nullable<int> _Ycnt;
		
		public PF_GET_SALESResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ncnt", DbType="Int")]
		public System.Nullable<int> Ncnt
		{
			get
			{
				return this._Ncnt;
			}
			set
			{
				if ((this._Ncnt != value))
				{
					this._Ncnt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ycnt", DbType="Int")]
		public System.Nullable<int> Ycnt
		{
			get
			{
				return this._Ycnt;
			}
			set
			{
				if ((this._Ycnt != value))
				{
					this._Ycnt = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
