<?xml version="1.0" encoding="utf-8"?><Database Name="dbBeautyCommsupport" Class="POSULDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=dbBeautyCommsupport;Persist Security Info=True;User ID=sa" SettingsObjectName="AutoPos.Properties.Settings" SettingsPropertyName="dbBeautyCommsupportConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.POS_UL" Member="POS_ULs">
    <Type Name="POS_UL">
      <Column Name="WH_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ABBNO" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PTDATE" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WORKDATE" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TMCODE" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UFLAG" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.trn_log_pos" Member="trn_log_pos">
    <Type Name="trn_log_pos">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="whcode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="workdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="sms" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>